spring.application.name=spring-board
spring.devtools.livereload.enabled=true


#TRACE, DEBUG, INFO, WWARN, ERROR
logging.level.net.likelion.bebc25=DEBUG

## JDBC 설정
spring.datasource.url =jdbc:mysql://localhost:3306/board_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

#스프링 구동 시 DB 초기화 스크립트 실행(s
spring.sql.init.mode=always